{% set name = "hdf5tools" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdf5tools-{{ version }}.tar.gz
  sha256: 234cd1bb42cd9fad16477e8357d788d9d6f56541e9ac663d3058337fb8667217

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - xarray >=2022.03.0
    - h5py >=3.6.0
    - hdf5plugin >=3.3.1
    - h5netcdf >=1.0.2
    - cftime

test:
  imports:
    - hdf5tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tethys-ts/hdf5-tools
  summary: Python hdf5 tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mullenkamp
