{% set name = "hdf5tools" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdf5tools-{{ version }}.tar.gz
  sha256: 510a029e21f6d69ab1a48b05fab65a59bdf8d13795bab138d9fd390f92cfe48c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - xarray >=2022.03.0
    - h5py >=3.6.0
    - hdf5plugin >=3.3.1
    - h5netcdf
    - cftime

test:
  imports:
    - hdf5tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tethys-ts/hdf5-tools
  summary: Python hdf5 tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mullenkamp
